sudo: false

language: python

services:
  - postgresql
  - mysql

python:
  - "2.7"

branches:
  only:
    - master

install:
  - pip install -U pip wheel setuptools
  # command to install requirements
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - python setup.py develop -q

before_script:
  # - export DISPLAY=:99.0
  # - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - psql template1 -c 'CREATE EXTENSION hstore;'
  - psql -U postgres -c 'CREATE DATABASE nodeshot_ci;'
  - psql -U postgres -d nodeshot_ci -c "CREATE EXTENSION postgis;"
  - mysql -e 'create database nodeshot_old_ci;'
  # try to avoid mysql has gone away errors
  - mysql -e "SET GLOBAL wait_timeout = 36000;"
  - mysql -e "SET GLOBAL max_allowed_packet=134209536;"
  - cd tests
  - ./manage.py migrate --noinput --no-initial-data

# command to run tests, e.g. python setup.py test
script:
  - coverage run --source=nodeshot runtests.py --keepdb

after_success:
  coveralls
archive: true
