language: python

services:
  - postgresql
  - mysql

python:
  - "2.7"

branches:
  only:
    - master

# command to install requirements
install:
  - pip install -r requirements.txt
  - pip install coverage coveralls selenium
  - python setup.py install
  - pip install MySQL-python

before_script:
  # - export DISPLAY=:99.0
  # - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - psql template1 -c 'CREATE EXTENSION hstore;'
  - psql -U postgres -c 'CREATE DATABASE nodeshot_ci;'
  - psql -U postgres -d nodeshot_ci -c "CREATE EXTENSION postgis;"
  - psql -U postgres -d nodeshot_ci -c "CREATE EXTENSION postgis_topology;"
  - mysql -e 'create database nodeshot_old_ci;'
  - cd tests
  - ./manage.py syncdb --noinput --no-initial-data
  - ./manage.py migrate --noinput --no-initial-data
  - ./manage.py collectstatic --noinput
  - ./manage.py loaddata initial_data
  # begin temporary workaround for django 1.6 LiveServerTestCase suckness
  - ./manage.py mail_debug &
  - ./manage.py loaddata test_profiles test_layers test_status test_nodes test_pages
  - ./manage.py runserver 0.0.0.0:8000 &
  - sleep 2 # give django server time to bind to sockets
  # end

# command to run tests, e.g. python setup.py test
script:
  - coverage run --source=nodeshot runtests.py

after_success:
  coveralls
